spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: back-end
    url: jdbc:postgresql://localhost:5432/db
    username: hello
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect